<a href="https://colab.research.google.com/github/aaryagore/ML_basics/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
kolhi_runs = np.array([45, 72, 33, 61, 88, 54, 40, 76, 92, 58])

In [3]:
print(kolhi_runs)

[45 72 33 61 88 54 40 76 92 58]


In [4]:
type(kolhi_runs)

numpy.ndarray

In [5]:
kolhi_runs.shape

(10,)

In [6]:
batters = np.array([[45, 72, 33, 61, 88],[55, 48, 70, 92, 60],[30, 44, 50, 78, 81]])

In [7]:
print(batters)

[[45 72 33 61 88]
 [55 48 70 92 60]
 [30 44 50 78 81]]


In [8]:
type(batters)

numpy.ndarray

In [9]:
batters.shape

(3, 5)

In [10]:
batters.ndim

2

In [11]:
batters.dtype

dtype('int64')

In [12]:
batters.size

15

In [14]:
batters.nbytes  #nbytes used to show memory consumption in bytes

120

In [15]:
kolhi_runs[0]

np.int64(45)

In [16]:
kolhi_runs[-3:]

array([76, 92, 58])

In [17]:
batters[1][2]

np.int64(70)

In [18]:
runs = np.array([45,72,33,61,88,54])

In [20]:
runs.reshape(2,3)

array([[45, 72, 33],
       [61, 88, 54]])

In [21]:
kolhi_runs + 10

array([ 55,  82,  43,  71,  98,  64,  50,  86, 102,  68])

In [22]:
kolhi_runs * 2

array([ 90, 144,  66, 122, 176, 108,  80, 152, 184, 116])

In [23]:
np.sum(kolhi_runs)

np.int64(619)

In [24]:
np.mean(kolhi_runs)

np.float64(61.9)

In [25]:
np.max(kolhi_runs)

np.int64(92)

In [26]:
np.min(kolhi_runs)

np.int64(33)

In [28]:
np.median(kolhi_runs)

np.float64(59.5)

In [29]:
np.std(kolhi_runs)

np.float64(18.886238376129853)

In [30]:
kolhi = np.array([45, 72, 33, 61, 88])

In [31]:
gill = np.array([55, 48, 70, 92, 60])

In [32]:
kolhi

array([45, 72, 33, 61, 88])

In [33]:
gill

array([55, 48, 70, 92, 60])

In [34]:
print(np.mean(kolhi))

59.8


In [36]:
np.mean(gill)

np.float64(65.0)

In [37]:
print(np.mean(gill))

65.0


In [38]:
kolhi > 50

array([False,  True, False,  True,  True])

In [39]:
gill > 30

array([ True,  True,  True,  True,  True])

In [40]:
kolhi[kolhi > 50]

array([72, 61, 88])

In [41]:
gill[gill > 80]

array([92])

In [45]:
toss_win = np.array([1, 0, 1, 1, 0, 1, 0, 1])

In [46]:
np.sum(toss_win)

np.int64(5)

In [48]:
economy = np.array([6.5, 7.1, 8.2, 5.8, 7.4])

In [49]:
np.min(economy)

np.float64(5.8)

In [50]:
scores = np.array([[180, 175, 190],[165, 200, 210],[150,185,170]])

In [51]:
print(scores)

[[180 175 190]
 [165 200 210]
 [150 185 170]]


In [53]:
np.mean(scores, axis=1) #axis = 1 removes mean for columns

array([181.66666667, 191.66666667, 168.33333333])

In [55]:
np.mean(scores, axis=0) #axis = 0 removes mean for rows

array([165.        , 186.66666667, 190.        ])

In [59]:
kolhi_runs = np.array([45,72,33,61,88,54,40,76,92,58])
avg_runs = np.mean(kolhi_runs)
print('Average:', avg_runs)
if avg_runs > 50:
  print('Player is in Form')
else:
  print('Player is Not in Form')

Average: 61.9
Player is in Form


In [91]:
#2
virat = np.array([56,78,90,45,68,56,44,30,56,45])
rohit = np.array([67,89,78,67,56,45,35,89,90,78])


In [78]:
#1
virat_kolhi = np.array([45,100,89,67,50,90,67,80,80,89])
last7 = virat_kolhi[-7:]
last7

array([67, 50, 90, 67, 80, 80, 89])

In [79]:
np.sum(last7)

np.int64(523)

In [80]:
np.mean(last7)

np.float64(74.71428571428571)

In [81]:
np.max(last7)

np.int64(90)

In [82]:
#2
virat = np.array([45,67,89,90,78,56,35,45,27,89])
rohit = np.array([44,80,79,90,78,56,34,88,97,88])

In [84]:
virat_sum = np.sum(virat)
print(virat_sum)

621


In [85]:
rohit_sum = np.sum(rohit)
print(rohit_sum)

734


In [87]:
if virat_sum > rohit_sum :
  print("Virat Kolhi scored more runs")
else:
  print("Rohit Sharma scored more runs")


Rohit Sharma scored more runs


In [88]:
virat_avg = np.mean(virat)
print(virat_avg)

62.1


In [89]:
rohit_avg = np.mean(rohit)
print(rohit_avg)

73.4


In [90]:
print(rohit_avg - virat_avg)

11.300000000000004


In [100]:
matches_kolhi_more = np.sum(virat > rohit)
print(matches_kolhi_more)

4


In [104]:
#3
team_runs = ([45,60,30],[50,70,40],[20,30,50],[60,40,80],[30,20,40])

In [108]:
best = np.max(total)
print(best)

180


In [109]:
total = np.sum(team_runs, axis = 1)
print(total)

[135 160 100 180  90]


In [111]:
match_total = np.sum(team_runs, axis = 0)
print(match_total)

[205 220 240]


In [121]:
#4
player = np.array([45,72,33,61,88,54,40,76,92,58])
print(player)

[45 72 33 61 88 54 40 76 92 58]


In [114]:
mean_player = np.mean(player)
print(mean_player)

61.9


In [115]:
std_player = np.std(player)
print(std_player)

18.886238376129853


In [116]:
var_player = np.var(player)
print(var_player)

356.69


In [118]:
cv = (std_player/mean_player)*100
print(cv)

30.510885906510264


In [119]:
if cv > 75:
  print('Player is consistent')
else:
  print('Player is inconsistent')

Player is inconsistent


In [122]:
#5
runs = np.array([1,4,0,6,2,1,4,0,1,6,2,1])
print(runs)

[1 4 0 6 2 1 4 0 1 6 2 1]


In [124]:
total_runs = np.sum(runs)
print(total_runs)

28


In [142]:
boundary_runs = np.sum(runs[(runs == 4) | (runs == 6)])
print(boundary_runs)

20


In [144]:
boundary_percent = (boundary_runs / total_runs) * 100
print(boundary_percent)

71.42857142857143
